In [46]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
import time

woc = WocMapsRemote(base_url="https://worldofcode.org/api/")

projects = [
    'gabinsane/multimodal-vae-comparison',
    'MansMeg/posteriordb',
    'markmfredrickson/optmatch',
    'statistikat/VIM',
    'FairRootGroup/FairRoot',
    'arfc/pride',
    'nexpy/nexpy',
    'tompollard/tableone',
    'geospace-code/pymap3d',
    'GeoKnow/LinkedGeoData'
]

list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head()

,sha1,project
0,034f34e1158ffb69f5ad4ceefeff4991e312abc8,gabinsane_multimodal-vae-comparison
1,03541d8d436a25eb9f0da8582930647a58168a6c,gabinsane_multimodal-vae-comparison
2,03a1e7075edfe00bea813019c58c9861bdc305ab,gabinsane_multimodal-vae-comparison
3,03d8331004cbdae249a2fea07837ca8e1dab88e4,gabinsane_multimodal-vae-comparison
4,04977864f89f12e320905b26a3732515ac675982,gabinsane_multimodal-vae-comparison

In [47]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

 10%|███▎                               | 180/1879 [03:04<28:58,  1.02s/it]

Got Errors {'0ac2919c2e13d0e389f878e8feed5f9f714b6ca3': 'Key 0ac2919c2e13d0e389f878e8feed5f9f714b6ca3 not found in /da5_fast/All.sha1c/commit_10.tch'}

 10%|███▍                               | 183/1879 [03:07<28:56,  1.02s/it]

Got Errors {'0e81f04db03fd179f481c86ddb654294951e5c13': 'Key 0e81f04db03fd179f481c86ddb654294951e5c13 not found in /da5_fast/All.sha1c/commit_14.tch'}

 10%|███▍                               | 186/1879 [03:10<28:50,  1.02s/it]

Got Errors {'1335afddd3fd0d56ecad04da27c4fd88f1e6e83b': 'Key 1335afddd3fd0d56ecad04da27c4fd88f1e6e83b not found in /da5_fast/All.sha1c/commit_19.tch'}

 12%|████▏                              | 225/1879 [03:50<28:10,  1.02s/it]

Got Errors {'41ad8e7ce824dcd85b5562db83b4a0e7426628bc': 'Key 41ad8e7ce824dcd85b5562db83b4a0e7426628bc not found in /da5_fast/All.sha1c/commit_65.tch'}

 12%|████▎                              | 231/1879 [03:56<28:08,  1.02s/it]

Got Errors {'4927737968016c5f7aff23bc38f16ca4489c1cd9': 'Key 4927737968016c5f7aff23bc38f16ca4489c1cd9 not found in /da5_fast/All.sha1c/commit_73.tch'}

 13%|████▍                              | 240/1879 [04:05<28:01,  1.03s/it]

Got Errors {'5483867dded9d3c3e773aecca3328778621e39b1': 'Key 5483867dded9d3c3e773aecca3328778621e39b1 not found in /da5_fast/All.sha1c/commit_84.tch'}

 13%|████▋                              | 251/1879 [04:16<27:43,  1.02s/it]

Got Errors {'627448992dfdaceb68596ca5d080e1b7f2a1eea5': 'Key 627448992dfdaceb68596ca5d080e1b7f2a1eea5 not found in /da5_fast/All.sha1c/commit_98.tch'}

 14%|████▊                              | 259/1879 [04:24<27:37,  1.02s/it]

Got Errors {'6e0cc80b0c54e3891f8cc6561eb932c41e0f42b2': 'Key 6e0cc80b0c54e3891f8cc6561eb932c41e0f42b2 not found in /da5_fast/All.sha1c/commit_110.tch'}

 15%|█████▏                             | 279/1879 [04:45<27:13,  1.02s/it]

Got Errors {'8bea08c8b417b36c637d1e40a61aff291122ae77': 'Key 8bea08c8b417b36c637d1e40a61aff291122ae77 not found in /da5_fast/All.sha1c/commit_11.tch'}

 15%|█████▎                             | 287/1879 [04:53<27:10,  1.02s/it]

Got Errors {'961bce6720fb526f4f9645fb86d60489afd1ea0c': 'Key 961bce6720fb526f4f9645fb86d60489afd1ea0c not found in /da5_fast/All.sha1c/commit_22.tch'}

 15%|█████▍                             | 291/1879 [04:57<27:04,  1.02s/it]

Got Errors {'9a7c5815b099b2fe28edd3c85c54228d0a23600c': 'Key 9a7c5815b099b2fe28edd3c85c54228d0a23600c not found in /da5_fast/All.sha1c/commit_26.tch'}

 16%|█████▍                             | 295/1879 [05:01<26:57,  1.02s/it]

Got Errors {'9f0dff037456294962d334573d3714b669e9520a': 'Key 9f0dff037456294962d334573d3714b669e9520a not found in /da5_fast/All.sha1c/commit_31.tch'}

 16%|█████▋                             | 306/1879 [05:12<26:56,  1.03s/it]

Got Errors {'ad3dacf7314d5ef589690036422616156990f04c': 'Key ad3dacf7314d5ef589690036422616156990f04c not found in /da5_fast/All.sha1c/commit_45.tch'}

 17%|█████▊                             | 313/1879 [05:20<26:41,  1.02s/it]

Got Errors {'b60e0372bb85d51d987b6a9c650d3e3327f335a1': 'Key b60e0372bb85d51d987b6a9c650d3e3327f335a1 not found in /da5_fast/All.sha1c/commit_54.tch'}

 19%|██████▌                            | 350/1879 [05:57<26:04,  1.02s/it]

Got Errors {'e63fca4b1b5823bd4a9c1779de53d26b154bdc53': 'Key e63fca4b1b5823bd4a9c1779de53d26b154bdc53 not found in /da5_fast/All.sha1c/commit_102.tch'}

 27%|█████████▎                         | 502/1879 [08:33<23:25,  1.02s/it]

Got Errors {'0d360c8a145bb1f0cd123ceeb13050a3b6fd73ee': 'Key 0d360c8a145bb1f0cd123ceeb13050a3b6fd73ee not found in /da5_fast/All.sha1c/commit_13.tch'}

 27%|█████████▍                         | 504/1879 [08:35<23:24,  1.02s/it]

Got Errors {'0dea8e225f132458a9ef9fb3048bb1f0c61be81b': 'Key 0dea8e225f132458a9ef9fb3048bb1f0c61be81b not found in /da5_fast/All.sha1c/commit_13.tch'}

 27%|█████████▌                         | 511/1879 [08:42<23:17,  1.02s/it]

Got Errors {'10ca3d6198b608c39a1422c746167d69d311b3f6': 'Key 10ca3d6198b608c39a1422c746167d69d311b3f6 not found in /da5_fast/All.sha1c/commit_16.tch'}

 29%|██████████                         | 542/1879 [09:14<22:53,  1.03s/it]

Got Errors {'1bbe4b3234fa41d57b2734d328ccdba0a00f968f': 'Key 1bbe4b3234fa41d57b2734d328ccdba0a00f968f not found in /da5_fast/All.sha1c/commit_27.tch'}

 29%|██████████▏                        | 547/1879 [09:19<22:42,  1.02s/it]

Got Errors {'1d59c094a035a96dfa6443e6adfb79e09ff17cd9': 'Key 1d59c094a035a96dfa6443e6adfb79e09ff17cd9 not found in /da5_fast/All.sha1c/commit_29.tch'}

 29%|██████████▎                        | 554/1879 [09:26<22:34,  1.02s/it]

Got Errors {'1ffe195b3bafdab59a5acf465a668069e360899c': 'Key 1ffe195b3bafdab59a5acf465a668069e360899c not found in /da5_fast/All.sha1c/commit_31.tch'}

 30%|██████████▌                        | 570/1879 [09:42<22:19,  1.02s/it]

Got Errors {'25b8d34c76b60f5dd58bff75bfa10feffdac7cfd': 'Key 25b8d34c76b60f5dd58bff75bfa10feffdac7cfd not found in /da5_fast/All.sha1c/commit_37.tch'}

 31%|███████████                        | 591/1879 [10:04<22:05,  1.03s/it]

Got Errors {'2dc14f2e25df5e3449508ddc49bd4375bb438299': 'Key 2dc14f2e25df5e3449508ddc49bd4375bb438299 not found in /da5_fast/All.sha1c/commit_45.tch'}

 32%|███████████▏                       | 599/1879 [10:12<21:48,  1.02s/it]

Got Errors {'30ca3da2841a41e3e9e2214c0c12cfbc80e18d6f': 'Key 30ca3da2841a41e3e9e2214c0c12cfbc80e18d6f not found in /da5_fast/All.sha1c/commit_48.tch'}

 34%|███████████▉                       | 642/1879 [10:56<21:05,  1.02s/it]

Got Errors {'3fdc9084e0e1a32a71529729434ccb2b6b3cdc41': 'Key 3fdc9084e0e1a32a71529729434ccb2b6b3cdc41 not found in /da5_fast/All.sha1c/commit_63.tch'}

 34%|████████████                       | 645/1879 [10:59<21:01,  1.02s/it]

Got Errors {'410efe64a059484280baf70b11af1bc4f01834d1': 'Key 410efe64a059484280baf70b11af1bc4f01834d1 not found in /da5_fast/All.sha1c/commit_65.tch'}

 35%|████████████▏                      | 652/1879 [11:06<20:53,  1.02s/it]

Got Errors {'4321a0528434284fbd15cf00ee6b5b008c34496d': 'Key 4321a0528434284fbd15cf00ee6b5b008c34496d not found in /da5_fast/All.sha1c/commit_67.tch', '434ff5c83f8836c4e2966d6422b3df937e961ac0': 'Key 434ff5c83f8836c4e2966d6422b3df937e961ac0 not found in /da5_fast/All.sha1c/commit_67.tch'}

 36%|████████████▊                      | 685/1879 [11:40<20:21,  1.02s/it]

Got Errors {'4e744dcdb91914ef06a6ac984930d325a983e67e': 'Key 4e744dcdb91914ef06a6ac984930d325a983e67e not found in /da5_fast/All.sha1c/commit_78.tch'}

 39%|█████████████▋                     | 732/1879 [12:28<19:31,  1.02s/it]

Got Errors {'5f391e9d1fc4f6a1fa3a2c1e18e581754a821160': 'Key 5f391e9d1fc4f6a1fa3a2c1e18e581754a821160 not found in /da5_fast/All.sha1c/commit_95.tch'}

 40%|█████████████▉                     | 747/1879 [12:44<19:17,  1.02s/it]

Got Errors {'63f9b084780fca30123e24ca7dd2a2ade89e2214': 'Key 63f9b084780fca30123e24ca7dd2a2ade89e2214 not found in /da5_fast/All.sha1c/commit_99.tch'}

 40%|██████████████                     | 755/1879 [12:52<19:16,  1.03s/it]

Got Errors {'6763430e1a4ed9c670096d1f93713cd0954b290f': 'Key 6763430e1a4ed9c670096d1f93713cd0954b290f not found in /da5_fast/All.sha1c/commit_103.tch', '677901f90620b198f493a018b5f03b7ec6c1ce17': 'Key 677901f90620b198f493a018b5f03b7ec6c1ce17 not found in /da5_fast/All.sha1c/commit_103.tch'}

 40%|██████████████                     | 758/1879 [12:55<19:08,  1.02s/it]

Got Errors {'6849a086aa8e24297c4cb0f1181265f03d217aa7': 'Key 6849a086aa8e24297c4cb0f1181265f03d217aa7 not found in /da5_fast/All.sha1c/commit_104.tch'}

 40%|██████████████▏                    | 760/1879 [12:57<19:04,  1.02s/it]

Got Errors {'691532a4302e795a6e794c18467ab375c8151c15': 'Key 691532a4302e795a6e794c18467ab375c8151c15 not found in /da5_fast/All.sha1c/commit_105.tch'}

 42%|██████████████▌                    | 785/1879 [13:23<18:37,  1.02s/it]

Got Errors {'71f7e7ddf00a948cf7124aabe33e6c2cedc385ae': 'Key 71f7e7ddf00a948cf7124aabe33e6c2cedc385ae not found in /da5_fast/All.sha1c/commit_113.tch'}

 43%|██████████████▉                    | 803/1879 [13:41<18:19,  1.02s/it]

Got Errors {'79701c684d5a72dca70f8fef2832c0e8b47759cb': 'Key 79701c684d5a72dca70f8fef2832c0e8b47759cb not found in /da5_fast/All.sha1c/commit_121.tch'}

 44%|███████████████▍                   | 826/1879 [14:04<17:55,  1.02s/it]

Got Errors {'81d0b889bc085cb53b402cc81081a6372c13c24c': 'Key 81d0b889bc085cb53b402cc81081a6372c13c24c not found in /da5_fast/All.sha1c/commit_1.tch'}

 46%|████████████████                   | 859/1879 [14:38<17:24,  1.02s/it]

Got Errors {'8db737dc876bbf67fc5053557874b9b39f04c36f': 'Key 8db737dc876bbf67fc5053557874b9b39f04c36f not found in /da5_fast/All.sha1c/commit_13.tch'}

 47%|████████████████▎                  | 877/1879 [14:57<17:03,  1.02s/it]

Got Errors {'938f094cd6fd1e0892b4bdb653848e041dcd4b2e': 'Key 938f094cd6fd1e0892b4bdb653848e041dcd4b2e not found in /da5_fast/All.sha1c/commit_19.tch'}

 47%|████████████████▍                  | 885/1879 [15:05<16:55,  1.02s/it]

Got Errors {'95d62cc9b06d03d5b5da226a963cccd4b45e070a': 'Key 95d62cc9b06d03d5b5da226a963cccd4b45e070a not found in /da5_fast/All.sha1c/commit_21.tch'}

 48%|████████████████▉                  | 909/1879 [15:29<16:31,  1.02s/it]

Got Errors {'9ed280e92766bdd6b5c709b08eea910a99ea2f88': 'Key 9ed280e92766bdd6b5c709b08eea910a99ea2f88 not found in /da5_fast/All.sha1c/commit_30.tch'}

 52%|██████████████████▎                | 980/1879 [16:42<15:19,  1.02s/it]

Got Errors {'b6c3dfe76f53c520d084350bb64cfbf9218404df': 'Key b6c3dfe76f53c520d084350bb64cfbf9218404df not found in /da5_fast/All.sha1c/commit_54.tch'}

 53%|██████████████████▍                | 988/1879 [16:50<15:08,  1.02s/it]

Got Errors {'b9562cf1c2c195cdf9ceb84eb09097ffa404446d': 'Key b9562cf1c2c195cdf9ceb84eb09097ffa404446d not found in /da5_fast/All.sha1c/commit_57.tch'}

 53%|██████████████████                | 1000/1879 [17:02<14:57,  1.02s/it]

Got Errors {'bd6849adf29f34a3c4a16a7dcc3319d2204427f6': 'Key bd6849adf29f34a3c4a16a7dcc3319d2204427f6 not found in /da5_fast/All.sha1c/commit_61.tch'}

 53%|██████████████████▏               | 1002/1879 [17:04<14:56,  1.02s/it]

Got Errors {'be5977992ae278a97c6135444fee808af267acdc': 'Key be5977992ae278a97c6135444fee808af267acdc not found in /da5_fast/All.sha1c/commit_62.tch'}

 54%|██████████████████▍               | 1020/1879 [17:23<14:41,  1.03s/it]

Got Errors {'c4d892bfa4915ae8bcf86cf9123034f044760b52': 'Key c4d892bfa4915ae8bcf86cf9123034f044760b52 not found in /da5_fast/All.sha1c/commit_68.tch'}

 55%|██████████████████▌               | 1025/1879 [17:28<14:34,  1.02s/it]

Got Errors {'c62e726bbea8e2ee8a0c5234fb47a59a5c3cd71a': 'Key c62e726bbea8e2ee8a0c5234fb47a59a5c3cd71a not found in /da5_fast/All.sha1c/commit_70.tch'}

 55%|██████████████████▋               | 1035/1879 [17:38<14:23,  1.02s/it]

Got Errors {'ca362d40a45b1dcf2061d9f4d52a858b5bef66cc': 'Key ca362d40a45b1dcf2061d9f4d52a858b5bef66cc not found in /da5_fast/All.sha1c/commit_74.tch'}

 58%|███████████████████▌              | 1082/1879 [18:26<13:33,  1.02s/it]

Got Errors {'d9ab1a8e6cc7523b2b174da7f9c56df6dfe62e88': 'Key d9ab1a8e6cc7523b2b174da7f9c56df6dfe62e88 not found in /da5_fast/All.sha1c/commit_89.tch'}

 58%|███████████████████▋              | 1090/1879 [18:34<13:27,  1.02s/it]

Got Errors {'dc7f66b525ef51dc12fe22a47606be031596a89b': 'Key dc7f66b525ef51dc12fe22a47606be031596a89b not found in /da5_fast/All.sha1c/commit_92.tch'}

 59%|███████████████████▉              | 1100/1879 [18:44<13:15,  1.02s/it]

Got Errors {'e02c99e80cba040ffad7023e6a03f382a3957e35': 'Key e02c99e80cba040ffad7023e6a03f382a3957e35 not found in /da5_fast/All.sha1c/commit_96.tch'}

 59%|████████████████████▏             | 1116/1879 [19:01<13:00,  1.02s/it]

Got Errors {'e660a728cb90a1d4c308787921ceec73670f1016': 'Key e660a728cb90a1d4c308787921ceec73670f1016 not found in /da5_fast/All.sha1c/commit_102.tch'}

 60%|████████████████████▍             | 1128/1879 [19:13<12:48,  1.02s/it]

Got Errors {'eb5a31095c37c68e599c81a6c0efec9d04c0c3d3': 'Key eb5a31095c37c68e599c81a6c0efec9d04c0c3d3 not found in /da5_fast/All.sha1c/commit_107.tch'}

 61%|████████████████████▊             | 1150/1879 [19:36<12:25,  1.02s/it]

Got Errors {'f2db638ada041f7c2c51d2dcd90584b209969a61': 'Key f2db638ada041f7c2c51d2dcd90584b209969a61 not found in /da5_fast/All.sha1c/commit_114.tch'}

 62%|████████████████████▉             | 1157/1879 [19:43<12:19,  1.02s/it]

Got Errors {'f4d5464e2ccf260b3c88ae1905bc4e69767b8b8b': 'Key f4d5464e2ccf260b3c88ae1905bc4e69767b8b8b not found in /da5_fast/All.sha1c/commit_116.tch'}

 62%|█████████████████████▏            | 1172/1879 [19:58<12:02,  1.02s/it]

Got Errors {'f9326424b7b6563273347fb635ba4b07b1ea7a98': 'Key f9326424b7b6563273347fb635ba4b07b1ea7a98 not found in /da5_fast/All.sha1c/commit_121.tch'}

 63%|█████████████████████▎            | 1177/1879 [20:03<11:57,  1.02s/it]

Got Errors {'faf68cfc8e46852a236f0373bd7cdb07cf5d1c13': 'Key faf68cfc8e46852a236f0373bd7cdb07cf5d1c13 not found in /da5_fast/All.sha1c/commit_122.tch'}

 63%|█████████████████████▎            | 1180/1879 [20:06<11:53,  1.02s/it]

Got Errors {'fc28afb4b19282c5d091942f6817b5b47cb5cc0e': 'Key fc28afb4b19282c5d091942f6817b5b47cb5cc0e not found in /da5_fast/All.sha1c/commit_124.tch'}

 69%|███████████████████████▍          | 1293/1879 [22:02<09:58,  1.02s/it]

Got Errors {'00d9014c11897afa008d245259558e62cb9087fd': 'Key 00d9014c11897afa008d245259558e62cb9087fd not found in /da5_fast/All.sha1c/commit_0.tch'}

 70%|███████████████████████▊          | 1318/1879 [22:27<09:33,  1.02s/it]

Got Errors {'150a6eb2dc7d1b63db65cccb59e7ee1af9bb25d9': 'Key 150a6eb2dc7d1b63db65cccb59e7ee1af9bb25d9 not found in /da5_fast/All.sha1c/commit_21.tch'}

 72%|████████████████████████▌         | 1357/1879 [23:07<08:53,  1.02s/it]

Got Errors {'3030de0d2c8a52ed896dee9766711aee2e4d50e3': 'Key 3030de0d2c8a52ed896dee9766711aee2e4d50e3 not found in /da5_fast/All.sha1c/commit_48.tch'}

 74%|█████████████████████████▏        | 1392/1879 [23:43<08:17,  1.02s/it]

Got Errors {'4bfcf2f2173bbbc924149f7bf4e6151928ce86c7': 'Key 4bfcf2f2173bbbc924149f7bf4e6151928ce86c7 not found in /da5_fast/All.sha1c/commit_75.tch'}

 75%|█████████████████████████▌        | 1412/1879 [24:03<07:58,  1.02s/it]

Got Errors {'5a89ab4daa87e46ee741d3ef0e7346a0aea9169c': 'Key 5a89ab4daa87e46ee741d3ef0e7346a0aea9169c not found in /da5_fast/All.sha1c/commit_90.tch'}

 76%|█████████████████████████▉        | 1433/1879 [24:25<07:36,  1.02s/it]

Got Errors {'68d7b41cfe431298e7fa17c61ca2c7384078603a': 'Key 68d7b41cfe431298e7fa17c61ca2c7384078603a not found in /da5_fast/All.sha1c/commit_104.tch'}

 78%|██████████████████████████▋       | 1474/1879 [25:07<06:54,  1.02s/it]

Got Errors {'8642df266d454280ea9a69c608faf16db3b40244': 'Key 8642df266d454280ea9a69c608faf16db3b40244 not found in /da5_fast/All.sha1c/commit_6.tch'}

 81%|███████████████████████████▌      | 1521/1879 [25:55<06:06,  1.02s/it]

Got Errors {'aa29eac2a36ccb72f19d139dbb20b446bf2e6b2b': 'Key aa29eac2a36ccb72f19d139dbb20b446bf2e6b2b not found in /da5_fast/All.sha1c/commit_42.tch'}

 82%|███████████████████████████▊      | 1534/1879 [26:08<05:52,  1.02s/it]

Got Errors {'b50db987fa553bdac49cb1a6a3e27cb04fa18502': 'Key b50db987fa553bdac49cb1a6a3e27cb04fa18502 not found in /da5_fast/All.sha1c/commit_53.tch'}

 84%|████████████████████████████▍     | 1571/1879 [26:46<05:14,  1.02s/it]

Got Errors {'d04466dfe10b49ccf92654dbf14ea54f04a83d90': 'Key d04466dfe10b49ccf92654dbf14ea54f04a83d90 not found in /da5_fast/All.sha1c/commit_80.tch'}

 84%|████████████████████████████▋     | 1587/1879 [27:02<04:59,  1.02s/it]

Got Errors {'dcfa5255f0b8fc78edf7018d4a6b7d9c79817aa8': 'Key dcfa5255f0b8fc78edf7018d4a6b7d9c79817aa8 not found in /da5_fast/All.sha1c/commit_92.tch'}

 98%|█████████████████████████████████▎| 1843/1879 [31:24<00:36,  1.02s/it]

Got Errors {'24b83209947cba207ea50c28e863dff6895eece9': 'Key 24b83209947cba207ea50c28e863dff6895eece9 not found in /da5_fast/All.sha1c/commit_36.tch'}

 99%|█████████████████████████████████▌| 1858/1879 [31:40<00:21,  1.03s/it]

Got Errors {'7e3021081c9402eadf92bb5dd3fb70ef079108dd': 'Key 7e3021081c9402eadf92bb5dd3fb70ef079108dd not found in /da5_fast/All.sha1c/commit_126.tch'}

100%|██████████████████████████████████| 1879/1879 [32:01<00:00,  1.02s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,034f34e1158ffb69f5ad4ceefeff4991e312abc8,608d6eb0d47316c88c6fdb43ce04e0ae63b59817,[4057cf61289ab2913704884d963d0d7647e6d45c],Gabriela Šejnová <g.sejnova@gmail.com>,1661779711,+0200,Gabriela Šejnová <g.sejnova@gmail.com>,1661779711,+0200,test_torchmmvae.py passe\n,034f34e1158ffb69f5ad4ceefeff4991e312abc8,gabinsane_multimodal-vae-comparison
1,03541d8d436a25eb9f0da8582930647a58168a6c,e26b83f873b7a7cbde2fe1518d679aa8a9066e0c,[62ed61628a8a787c5262ea225a7bb1ee1aaf03e0],Gabriela Šejnová <g.sejnova@gmail.com>,1664540067,+0200,Gabriela Šejnová <g.sejnova@gmail.com>,1664540067,+0200,mnist_svhn vis and labelled tsne\n,03541d8d436a25eb9f0da8582930647a58168a6c,gabinsane_multimodal-vae-comparison

In [53]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '034f34e1158ffb69f5ad4ceefeff4991e312abc8', 'tree': '608d6eb0d47316c88c6fdb43ce04e0ae63b59817', 'parent': ['4057cf61289ab2913704884d963d0d7647e6d45c'], 'author': 'Gabriela Šejnová <g.sejnova@gmail.com>', 'author_time': 1661779711, 'author_tz': '+0200', 'committer': 'Gabriela Šejnová <g.sejnova@gmail.com>', 'committer_time': 1661779711, 'committer_tz': '+0200', 'message': 'test_torchmmvae.py passe\n'}

In [54]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [57]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,geoknow_linkedgeodata,034f34e1158ffb69f5ad4ceefeff4991e312abc8,Gabriela Šejnová <g.sejnova@gmail.com>,1661779711,test_torchmmvae.py passe\n

In [69]:
#mode a means append, so you have all your projects in the same file
yournetid='sbombry1'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=',', mode='a', header=False)

In [37]:
summary = df_commit_data.groupby('project').agg(
    num_commits=('commit', 'nunique'),
    num_authors=('author', 'nunique'),
    max_time=('author_time', 'max'),
    min_time=('author_time', 'min'),
)
summary

,num_commits,num_authors,max_time,min_time
project,,,,
arfc_pride,995,14,1740328556,1576622284
fairrootgroup_fairroot,7215,99,1774830205,1216626209
gabinsane_multimodal-vae-comparison,432,9,1747690487,1624959492
geoknow_linkedgeodata,431,18,1732125354,1359478118
geospace-code_pymap3d,1339,49,1751955558,1407040083
mansmeg_posteriordb,1290,40,1758720825,1554791725
markmfredrickson_optmatch,1967,29,1772727653,1307046210
nexpy_nexpy,3453,22,1774644547,1369843716
statistikat_vim,955,31,1775046232,1378979956
tompollard_tableone,641,20,1772227595,1494858965

In [38]:
# Mnaual github review (stars, forks, last_commit)
# Project          | Num_stars | Num_forks | Last_commit_Date 
# arfc_pride             3           7        Feb 11th 2025
# Fairrootgroup          70          100      Aug 6th 2025
# Multimodal-vae         34          11       May 19th 2025
# linkedgeodata          162         33       Sep 29th 2024
# pymap3d                445         88       Jun 21st 2026
# posteriordb            232         52       Sep 25th 2026
# optmatch               50          14       Sep 24th 2026
# nexpy                  53          25       Sep 21st 2026
# vim                    93          15       Sep 22nd 2026
# tableone               197         52       Feb 10th 2026